theme: jekyll-theme-minimal
include: _posts
title: Hacklog
author: Manuel Broncano
description: > # this means to ignore newlines until "baseurl:"
  A collection of my personal hacks
  
github_username:  mbroncano # DO NOT include the @ character, or else the build will fail!
show_excerpts: true # set to false to remove excerpts on the homepage
