theme: minima
title: HackBook
author: Manuel Broncano
#email: manuel@manuelbroncano.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of my personal hacks
  
# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  mbroncano # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
